# 📋 APPLICATION-SERVICE.yml
server:
  port: 8082
  # 🔥 This ensures Swagger uses the Gateway's address (8080) for testing
  forward-headers-strategy: framework

spring:
  application:
    name: APPLICATION-SERVICE

  # 🐇 RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://localhost:3306/application_db
    username: root
    password: Shivraj@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 🔬 Monitoring (Zipkin LATEST FORMAT ✅)
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"

# 📄 Swagger Optimization
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    use-root-path: true

jwt:
  secret: finflow_super_secure_jwt_secret_key_2026_project_backend
  expiration: 86400000

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

