server:
  port: 8082

spring:
  application:
    name: APPLICATION-SERVICE

  datasource:
    url: jdbc:mysql://mysql:3306/application_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  zipkin:
    base-url: http://zipkin:9411

management:
  tracing:
    sampling:
      probability: 1.0

jwt:
  secret: finflow_super_secure_jwt_secret_key_2026_project_backend
  expiration: 86400000

eureka:
  instance:
    prefer-ip-address: true
    hostname: application-service

  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
