server:
  port: 8083

spring:
  application:
    name: DOCUMENT-SERVICE

  datasource:
    url: jdbc:mysql://mysql:3306/document_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  zipkin:
    base-url: http://zipkin:9411

management:
  tracing:
    sampling:
      probability: 1.0

file:
  upload-dir: /app/uploads

jwt:
  secret: finflow_super_secure_jwt_secret_key_2026_project_backend
  expiration: 86400000

eureka:
  instance:
    prefer-ip-address: true
    hostname: document-service

  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
